### ISSUE TITLE
Unreliability of Upplay with Album Arts

### ISSUE THREAD

**Issue by Buellerich** [medoc92/upplay#55] opened 2016-12-27 19:39 UTC
Bonjour,

I am running Upplay with Minimserver (both newest versions).
Upplay shows Album Arts only from time to time in an unrelaible fashion. Also the progress pointer below the album arts window seems to move by random only. Sometimes, when an album is sent to playlist, the Album Arts shows up for half a second and than disappears.

Sascha

**Comment by medoc92** [comment] 2016-12-27 20:02
What media renderer are you using ? I think that album art updates actually come from the renderer.

**Comment by Buellerich** [comment] 2016-12-27 20:12
Thanks a lot for your quick response.
I am using JPlayStreamer on a Single PC setup. That means that Minimserver is local. OS is Windows 10.
I have also Kazoo installed as control point, which is rendering the Cover Arts at the moment.
On the Jplay Forum, you can read that some users had the same issue. (http://jplay.eu/forum/index.php?/topic/2148-best-sounding-control-point-apps-to-use-with-jplaystreamer/)
A lot of people inclusive myself prefer UPPLAY due to sound quality.

best regards

Sascha

**Comment by medoc92** [comment] 2016-12-28 08:09
I tried to install jplay on my win7 instance (which runs in a virtual machine), with no success: jplaystreamer does not start (the service is marked as 'stopped' in task manager). I have no idea of what may be happening, so can't do anything more, except if you have an idea of what may be causing the problem.

**Comment by Buellerich** [comment] 2016-12-28 11:57
Thanks again a lot for your efforts, but JPlayStreamer requires Windows 8 or later.

**Comment by medoc92** [comment] 2016-12-28 14:22
Ok. So I managed to install JPlay on a win10 virtual instance, and I was not able to reproduce your problem. The only issue I am seeing is that the zoomed image (the one you get when you hover about the thumbnail) appears to be unstable when it is too big.

Also, about the time updates, have you checked about this issue (a note on the upplay/windows page) ?:

    NOTE: If upplay mostly works but its state does not update (e.g. no time progress), 
     you probably need to allow incoming connections through the Windows Firewall (UPnP 
     state update events need HTTP connections from the player to the control point).

I saw that your set up was all on the same PC, but, actually, depending on some networking details and firewall implementation, it's quite possible that the time update connections from Renderer to Control Point have to go through the firewall anyway.

If you are able to be more specific about the album art issue (maybe it depends on the file type, or if the image is embedded in the stream or separate, etc.?), I'll take another look.

**Comment by Buellerich** [comment] 2016-12-28 20:26
Bonsoir et merci encore und fois.

Ok, the firewall might be a good point to start with. I saw however that all relevant apps and processes (inclusive of upplay) have been defined as allowable exceptions for the firewall. But anyhow I will disengage it.

Regarding the album art  issue I have never been able to get a zoomed image. If I choose minim server I can click on conductor, or composer, or in my case on 5albums, which is written in blue. When I click on 5 albums I am getting a list of these albums without an album art preview for these albums as you would for example get with Kazoo. If you choose one of these albums and right click and you choose send to playlist you see the album art for about 0,5 seconds above the playlist. Then it disappears again and you see the note signal again.

Best regards

Sascha

**Comment by medoc92** [comment] 2017-01-01 17:13
I tried again, and I just can't reproduce the album art issue. 

Upplay does not show album art in the right part (the albums lists etc.), this was discussed, and it seems that a majority of people prefer to see as many entries as possible than use space for images. Maybe I'll implement an alternate mode one day.

But when a track is playing, I do get the album art display, stable, and I can hover and zoom. The only difference I can see between your setup and mine is that my minimserver is on another machine. I have no reason to believe that this can make a difference though (but surprises sometimes occur). I have to admit that I am too lazy to try a local install of minimserver.

**Comment by Buellerich** [comment] 2017-01-02 13:12
Hi and thanks again for your efforts.

Until mid of January I will have no possibility to give it another try with different Firewall adjustments. Then, however, I will try it again, even with an additional PC.
The Pictures were not stored as an extra file in the Album Folder.

So, I will report again mid of January.

I have to admit that the construction of a local Server (minimstream) is somewhat strange. On the other hand Computer Audio is  a world on it's own and Sound Quality depends on many factors. I would have never thought that the choice of a control Point matters, but obviously, it does. 
On:  http://jplay.eu/forum/index.php?/topic/2148-best-sounding-control-point-apps-to-use-with-jplaystreamer/page-4
you can see that other users had the same problems, in spite of not using local Servers. But your control Point is praised for it's Sound Quality always. So, Keep your heading, I will come back in two weeks.

Sascha

**Closed** 2017-02-10 07:16 UTC
