### ISSUE TITLE
Playback Stops At The End Of A Track

### ISSUE THREAD

**Issue by JazzDoc** [medoc92/upplay#42] opened 2016-08-23 02:17 UTC
I've been trying out Upplay with JRiver Media Center 20/JPLAYStreamer. Sounds good but I just don't seem to be able to play an album all the way through. Playback stops at the end of a track, perhaps after the first, sometimes after the second.

I have tried out Windows versions of Linn Kinsky and Linn Kazoo and both work fine and will play through an entire album so seems like the issue is with Upplay. I like the minimal approach of Upplay so would like to get this resolved and go back to using it.

Can you help me to resolve this please?

**Comment by medoc92** [comment] 2016-08-23 19:37
Hi,

I get the feeling that I already heard of this problem and that we had found a solution, but I don't remember precisely, and I can't find a trace of it...

What upplay version are you using ?

**Comment by JazzDoc** [comment] 2016-08-23 23:33
Hi Jean-Francois

 

Thank you for your reply. It is much appreciated.

 

I am using the latest Windows version of Upplay, which I am running on Windows Server 2012 R2. I use two computers in my setup. Other software that I use is JRiver Media Center 20 as a server, together with JPLAY (http://jplay.eu/), Audiophile Optimizer (http://www.highend-audiopc.com/audiophile-optimizer), Fidelizer Pro (http://www.fidelizer-audio.com/) and Process Lasso Server x64 (https://bitsum.com/process-lasso-audiophiles-guide/) One of my two PCs is used as a Control PC, the other as an Audio PC. I presume you will be familiar with the dual PC setup, but if not, may I suggest that you visit the JPLAY website and refer to their manual. I previously used Bug Head Infinity Blade and while it produced a great sound, it was very inconvenient to use.

 

Upplay is strongly recommended by Marcin, the author of JPLAY. You will find his recommendation on the JPLAY Forum at:

 

http://jplay.eu/forum/index.php?/topic/2148-best-sounding-control-point-apps-to-use-with-jplaystreamer/

 

It would be great if you would consider becoming a member of the JPLAY Forum, and introducing yourself as the author of Upplay, which I presume you are! Marcin is right in his recommendation. Upplay sounds very good.

 

I have to tell you that I really don’t understand computer audio. I simply follow instructions given to me by kind members of the JPLAY Forum. I have however managed to solve the problem that I experienced of not being able to change from one track to the next in an album without playback stopping. I changed the DAC Link and Buffer values in JPLAY settings and everything now works fine. I don’t understand why it worked after this change. I moved as close to the JPLAY default settings as I could. It was however, interesting that prior to changing the settings, Linn Kinsky and Linn Kazoo would both work without any problems. I’m glad I’ve managed to get Upplay to work as it sounds much better than either of the Linn applications.

 

The only problem I have now is using the search function in Upplay. When I select a list of artists from the server and scroll through the list of artists in alphabetical order, the scrolling keeps going back to the top of the list. I hope I will figure out how to solve this one but if you have any advice on how best to use the search function, I would be most grateful.

 

Hope to see you at the JPLAY Forum

 

Best wishes

 

Simon

**Comment by medoc92** [comment] 2016-08-26 20:08
Hi,

Could you please describe exactly what you are doing when you get the search issue (exact steps)  ? I can't seem to be able to reproduce it.

**Comment by JazzDoc** [comment] 2016-08-26 22:46
Hi Jean-Francois. Thanks for your reply.

 

When I was searching for an artists by using the down cursor key, the list would scroll down, perhaps to around L or M in the alphabet, and would then revert to the beginning of the list, starting with A.

 

There is of course, an easier way to do it. As I have a large collection, when I first run Upplay, it takes a couple of minutes to compile a list of artists or albums. When I find the artist that I want, rather than left click on the artist name, I right click and select to open in a new tab. This keeps the original list of artists or albums intact. Problem solved!

 

I really am very impressed with Upplay. Congratulations on and thanks for a fine piece of software.

**Comment by medoc92** [comment] 2016-08-31 07:55
I am glad that you found a workaround for your issue. 

Unfortunately, I could not reproduce it. I looked at the code, and did not find what could cause the problem.

There is an issue with big directory updates: the interface may appear frozen for some time while upplay updates the content. This becomes significant, depending on the machine speed, around 5000 displayed entries. I would like to fix this, but I could not find a reasonably simple solution.

Closing the issue for now, as there is nothing I seem to be able to do about it.

**Closed by medoc92** 2016-08-31 07:55 UTC

**Comment by JazzDoc** [comment] 2016-08-31 09:42
The playback issue of stopping between tracks became a problem again. I solved it by disabling power saving options for the network cards in my two laptops. Seems fine now.

 

Do you think that Upplay used with Minimserver will produced a better sound quality than Upplay with JRiver Media Center?

**Comment by medoc92** [comment] 2016-08-31 10:45
JazzDoc writes:
 > The playback issue of stopping between tracks became a problem again. I solved
 > it by disabling power saving options for the network cards in my two laptops.
 > Seems fine now.
 > 
 > 
 > 
 > Do you think that Upplay used with Minimserver will produced a better sound
 > quality than Upplay with JRiver Media Center?

The only thing which can have an effect on sound quality (for the same
music files) is what happens between the (asynchronous!) USB receiver and
the speakers. Everything before is just stuffing data in the pipes. If the
stuffing goes bad it will produce either silence or obvious noises, not a
subtile degradation.

The only sensitive part of the purely digital section of the system is the
clock (re)generation between the USB receiver and the DAC: that's where
jitter is gained or lost. Then the DAC quality is important of course, and
further down we are back to "classical" analog issues.

So JRiver vs Minimserver will make no difference in audio quality (except
possibly if there is transcoding involved, but you generally want to avoid
this anyway). It's all a matter of convenience.
